<?php
error_reporting(0); //Error gizliyoruz
header('Content-Type: text/html; Charset=UTF-8'); //Sayfayı utf8 yapıyoruz
@$veri = htmlentities(trim(strtolower($_GET['grd'])), ENT_QUOTES, 'UTF-8'); //kullanıcıdan girdiyi aldık

$dizi = array( //sözler array
"Ağlamayınca değil, kadını ağlatmayınca adam olursun.",
"Aşk her erkeğe yakışmaz, aşk adam olana yakışır…",
"Gözünü ve gönlünü aynı kişiye teslim eden adam, adamdır.",
"Firari saatlerin ardından gelen isyankar sokakların tövbekar evlatlarıyız diye her haksızlığa tahammül edecek halimiz yoktur.",
"Düşmanlarımızın çokluğu, bizim adamlığımızdandır.",
"Bendeki yerini herkes kendi belirler. Bir bakarsın solumdasın, bir bakarsın yolunda.",
"Endamın yetmez, beyin şart şekerim.",
"Beni başkalarına bırakma, görürsen dayanamazsın.",
"Ederinden fazla değer soytarıyı kral eder.",
"Eskiden altını çizdiklerimin şimdi ise üstünü çiziyorum.",
"Kusura bakmayın, kusurlarınıza bakın!",
"Ağır geliyorsa benimle yaşam kapı orada ikile paşam.",
"Sahne senin devam et ben çıkmayım dua et.",
"Gölgene de lafım yok. O da seni adam sanıp peşinden geliyor.",
"Adımı avucuna yaz hatırladıkça yalarsın.",
"Yalnız olmak yanlış kalpte olmaktan iyidir.",
"Kaç promil eder şerefin? Söyle ona göre kaldırayım kadehimi!",
"Büyük balonların eceli, küçük iğnelerdir.",
"Seni öyle bir severim ki; akşam akşam gündüz olursun içimde…",
"Sadece gülüşümü yakala, öfkem sana ağır gelir.",
"Arkamdan konuşanların hepsi arkamda takılmaya devam etsin…",
"Dur hemen gitme! Daha ömrümü yiyecektin.",
"Egosunu öyle beslemiş ki; karakteri aç kalmış.",
"Sende haklısın. Adamlığın kadar konuş dedim diye bu susmalar.",
"Senin marka olduğun yerde etiketi ben koyarım!",
"Nerede beni unuttuysanız orada kalın tekrar gelip alamam sizi.",
"Otobüsün bile peşinden koşmadım. Sen kimsin?",
"Yüz verip adam ettiysem, sıfırla çarpar yok ederim.",
"Şerefin kadar konuş desem, ömür boyu susacak insanlar tanıyorum.",
"Kendime yakışanı severim. Herkese yapışanı değil.",
"Bu saatten sonra ben başkası için yazarım, sen kendin için okursun!",
"İtle köpekle uğraşacak olsaydık veteriner olurduk.",
"Erkekliğin gücü bir kadına vurmakta değil; 1 kadına vurulmaktadır.",
"Canım, karakterin yere düşmüş onu bir alıver oradan.",
"Çok talibim var diyenler; sevinmeyin! Ucuz malın alıcısı çoktur.",
"Aşk acısı taşımayan yürek; ya deliye aittir, ya ölüye.",
"Bir gün bana gel diyeceksin. Söz geleceğim. Ama görmezden.",
"Bana kalbimdesin deme, bilirsin kalabalıkları sevmem.",
"Esmeyi bilmedikten sonra rüzgâr değil fırtına olsan ne yazar.",
"Gidişine illa bir isim konulacaksa, mal kaybı diyelim.",
"Dünya âleminin derdi ben olmuşum, demek ki zamanında iyi koymuşum.",
"Aklımdan geçtin gittin, kim bilir yine kime gidiyordun.",
"Üzülme, seni unuttuğumu sandın, her köpek havladığında aklımdasın…",
"Acılarım katlanılmaz değil ama bir de tuz basanı var.",
"Bana yol vermeyi düşünmeden önce. Sana verdiğim yolda yürümeyi öğren.",
"Kendini kalp mi sandın sevgili? Atmadan duramıyorsun!",
"Bana hava atacağım diye kendini kasma! Damarındaki kanın bile bana hasta.",
"Bize yeni düşmanlar lazım. Eskileri hayranımız oldular.",
"Sana biraz adam ol diyeceğim seni de zor durumda bırakmak istemiyorum.",
"Kendini bir bok sananlar; emin olun sandığınız gibisiniz.",
"Eğer niyetin yoksa adam gibi sevmeye, ben de mecbur değilim çocuk büyütmeye.",
"Gidiyor musun? Git! Soytarısı terk etti diye, kralın sarayı yıkılmaz.",
"Değmeyen birine dönüp bakmam. Adamsa notunu hayvansa otunu verir giderim.",
"Bazı insanlar hep ‘kaptan’ olurlar, söz konusu ‘dümen çevirmek’ olunca.",
"Çok laf sokuyorsun diyorlar ne yapayım hayatıma burnunu sokanlara şiir mi yazayım.",
"Bugün senin için bir şey yapmıyorsam dün elimden geleni yaptığım içindir.",
"Boşuna uğraşmayın; ana sütüyle adam olmayan kişi inek sütüyle ancak öküz olur.",
"Seni getiren leyleğin, sende bıraktığı ufak bir izdi, kuş beyinli olman.",
"Sildim hayatımdan saçma insanları sadece önümdeki gerçeklere bakıyorum.",
"Erkeklerin hepsi öküz değil, sen ahırın kapısında dolaşıyorsun güzelim.",
"Ne kadar sevdin diye soruyorlar. Hep aynı cevabı veriyorum, “HAK ETMEDİĞİ” kadar.",
"Bilirsin ben çok cimri biriyimdir, onun için kimseyle paylaşamam seni…",
"Canımı yakacak kadar cesareti olanın, sonuçlarına katlanacak kadar da gücü olmalı.",
"Uzak dur çek elini benden, senin gibi seviyesizleri çok geride bıraktım ben.",
"Sen! Pardon siz mi demeliydim? Siz kaç yüzlüydünüz? Ben yanlışlıkla hanginizi sevdim?",
"Yokluğunun iki yakasını bir araya getirip; varlığını ilikler misin ömrüme.",
"Bazı insanlar kitle üretim yapan fabrika ürünü gibi ambalaj farklı ama kalite aynı…",
"Herkese gerektiği değeri vereceksin öküze kravat takmanın bir alemi yok.",
"Aşkı tahteravalli olarak düşünün. Birinin sevgisi ağır basarsa diğerinin kıçı kalkar.",
"Minareden düşenin parçası bulunur, bulunur da; gönülden düşenin parçası bulunmaz.",
"Neden mutlu olamama bozuluyorsunuz ki; bana doğan güneş siz batıyor mu?",
"Oralarda benden yok bir düşünsen anlarsın. Buralarda senden çok var görsen şaşarsın.",
"Bin sene de okusam, ne biliyorsun diye sorsalar bana haddimi bilirim derim.",
"Bazen diyorlar: Çok ağır konuşuyorsunuz. Napalım şerefsizlik yapana şiir mi yazalım?",
"Yanımızda olması gerekenler zaten yanımda, defolup gidenler kimin umrunda.",
"Küsmek ve darılmak için bahaneler aramak yerine, sevmek ve sevilmek için çareler arayın.",
"Piyangonun sana çıkmadığına çok şaşırdım hâlbuki bütün numaralar sendeydi.",
"Bir erkek, bir bayandan daha çok trip atıyorsa o ilişkinin beyin ölümü gerçekleşmiş demektir.",
"Herkes pinokyo gibi insana dönüşme şansı bulamadı, kimileri hala odun kaldı.",
"Etme sırtını duvardan başkasına emanet en kralının bile içinde vardır bir nebze ihanet.",
"Dur beynimi çıkarayım da eşit şartlarda konuşalım demek istediğim insanlar var.",
"Yok, artık sana ait tek zerre bünyemde. Sen koca bir hiç oldun bende, ettiğin tek cümle ile!",
"Hayat bana hiç yeşil ışık yakmadı sorun değil, ben zaten hiç kırmızıda durmadım.",
"Siz benim tellerime, hangi notadan vuruyorsanız, ben o makamdan çalıp söylerim… Sıkıntı yok.",
"Ne kralına giderim, ne alayına… Bir durum varsa kralı da gelir ayağıma alayı da…",
"Hiç bir zaman yüksekte görmedik kendimizi, sadece gereksiz insanlar için düşürmedik seviyemizi.",
"Dilerim ki, bir gün benden yana şikâyet ettiği ne varsa onlara muhtaç olmasaydın.",
"Kendini dünyalar kadar değerli zannedenlere kısa bir not: dünya beş para etmiyor.",
"Gitmeyi tercih edenlerin ardından, el sallayın ki; artık sadece bir ‘el’ olduklarını daha iyi görsünler.",
"Dilini terbiye etmeden önce yüreğini terbiye et; çünkü söz yürekten gelir, dilden çıkar.",
"İçemediğin rakıyı bardağına, yapamayacağın sözü diline, sevemeyeceğin insanı gönlüne koymayacaksın.",
"Ya geç karşıma ortalığı sevginle inlet, ya da çekil kenara adam gibi nasıl sevilir seyret.",
"Arkamdan konuşan insanlar, konuşmaya devam edin. Küçük insanlar konuşur, büyük insanlar konuşulur.",
"Ben kimseye beni sevsin diye soytarılık yapmam. Ya sever bildiği gibi, ya gider geldiği gibi.",
"Ben en azından katilimi tanıyorum. Fakat sen bir gün sevilmediğin bir yürekte, kim vurdu ya gideceksin.",
"Çevrem çok geniş, diyenlere kısa bir not: 10 tane 10 kuruş 1 lira eder, 2 tane 50 kuruş da!",
"Aldattıktan sonra köpekler gibi pişmanım deyip, geri dönen sevgiliye, kalp değil bir parça kemik verilir.",
"İnsanlara daha ne kadar salak olabilirsin diye sormayın. Yarış zannedip sınırı zorlayanlar var.",
"Umutlara kanma umutlar bir gün imkânsızlaşır, hayatı tozpembe yaşıyorum sanma her renk bir gün siyahlaşır.",
"Kızlar erkeklerin “gelirlerine” erkekler kızların “giderlerine” baktığı sürece, biri gelir biri gider.",
"Yanlış kişiye “senden elektrik aldım” dersen, nasıl biri olduğunu sana faturayı kestikten sonra anlarsın!",
"Siz kumarda kazanan aşkta kaybeder yalanına inanın! Unutmayın ki; kumarda kazananlar aşkı satın alıyorlar.",
"Yol gidenindir, her gidenin ardından ağlayamam! Maalesef benim yüreğim ahır değil her öküzü oraya bağlayamam.",
"Kapatmaya gücünün yetmeyeceği kapıyı ardına kadar açma, açmaya yüzünün yetmeyeceği kapıyı da tamamen kapatma.",
"Kendini beğenmiş insanları severim. Hiç kimsenin beğenmediği pekguzelsozler.com bir şeyi beğenmek, ayrıcalıktır.",
"Aslında insanlar seni hayal kırıklığına uğratmıyor… Sadece sen, yanlış insanlar üzerinde hayal kuruyorsun…",
"Zor severim ama çok severim! Gerekirse ölebilirim hak edene değeri neyse veririm, yanlışını görürsem tarihe gömerim…",
"Karakterim ve tavrımı birbirine karıştırmayınız! Karakterim “kim olduğumla” ilgilidir, tavrım “sizin kim olduğunuzla.",
"Senin gibi bozukları kumbarada biriktirir, geleceğe yatırım yaparım. Haa çok mu sıkıştım; hiç düşünmem hemen harcarım.",
"Eski sevgilim, marketten hıyar aldığımı görünce; aynı sen dedi. Şimdilik yanıt vermedim ama elbet evde kaşar bitecek.",
"Bırakın ucuz lafları. Benim pahalıya mal olmuş suskunluklarım var. Sustum mu, suratına değil yüreğine vurur cümlelerim.",
"Hesabı olanlar sanmasın kapandı defterler. Tek tek yazıyorum her birini bir kenara. İyi kötü, bir gün ödenecek bedeller.",
"Attığınız ya da atacaklarınız kazıkları saklıyorum, saklıyorum ki gün gelip bana döndüğünüzde sizi ağırlayacak yerim olsun."); 

if(strcmp($veri,"söz")== 0){ //Kullanıcı "söz" girdiyse
$dizis = count($dizi)-1; //sayı bul
echo $dizi[rand(0,$dizis)]; //random bir veri yolluyoruz
	}


?>